### ISSUE TITLE
Extend subOfNumber function to allow for negative numbers in sumOfNumbers.js

### ISSUE THREAD

**Issue by juanbecerra0** [Turnout-Activism/InternPractice#104]
The sumOfNumbers function will always return 0 if the input is less than or equal to 0. I'd like to extend this function to iterate backwards given a negative number. For example, an input of -5 would result in -15 since

(-5) + (-4) + (-3) + (-2) + (-1) = -15

**Comment by iamamonte** [comment]
Yes, indeed. Thanks. When you've entered the PR, please link it to this issue.
